name: Auto PR Create

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  MERGE_TARGET_BRANCH: prod
  PR_TITLE: Main to Prod PR

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create Pull Request
        run: |
          gh pr create -B $MERGE_TARGET_BRANCH -t $PR_TITLE -b "Sample PR"
