name: Auto PR Create

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  BASE_BRANCH: main
  TARGET_BRANCH: prod
  PR_TEMPLATE: .github/pr_template.md

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Check if PR exists
        run: |
          echo "EXIT_PR_COUNT=$(gh pr list -B ${{ env.TARGET_BRANCH }} -H ${{ env.BASE_BRANCH }} | wc -l)" >> $GITHUB_ENV

      - name: Create Pull Request
        if: ${{ env.EXIT_PR_COUNT == 0 }}
        run: |
          gh pr create \
          -B "${{ env.TARGET_BRANCH }}" \
          -H ${{ env.BASE_BRANCH }} \
          -t "${{ env.BASE_BRANCH }} to ${{ env.TARGET_BRANCH }} PR" \
          -F "${{ env.PR_TEMPLATE }}"
