name: Auto PR Create

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  MERGE_TARGET_BRANCH: prod
  PR_TITLE: Main to Prod PR
  PR_TEMPLATE: .github/pr_template.md

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create Pull Request
        run: |
          pwd
          ls -a
          ls -a .github
          gh pr create -B "${{ env.MERGE_TARGET_BRANCH }}" -t "${{ env.PR_TITLE }}" -F "${{ env.PR_TEMPLATE }}"
